### ISSUE TITLE
NullPointerException thrown by InteractiveBrokersBroker on startup.

### ISSUE THREAD

**Issue by rterp** [rterp/SumZeroTrading#4]
java.lang.NullPointerException
	at com.sumzerotrading.broker.ib.InteractiveBrokersBroker.getDirName(InteractiveBrokersBroker.java:444)
	at com.sumzerotrading.broker.ib.InteractiveBrokersBroker.createDir(InteractiveBrokersBroker.java:437)
	at com.sumzerotrading.broker.ib.InteractiveBrokersBroker.loadOrderMaps(InteractiveBrokersBroker.java:425)
	at com.sumzerotrading.broker.ib.InteractiveBrokersBroker.<init>(InteractiveBrokersBroker.java:117)
	at com.sumzerotrading.interactive.brokers.client.InteractiveBrokersClient.<init>(InteractiveBrokersClient.java:80)
	at com.sumzerotrading.interactive.brokers.client.InteractiveBrokersClient.getInstance(InteractiveBrokersClient.java:65)
	at com.sumzerotrading.ib.example.trading.TradingExampleWithOrderStatusListener.placeFuturesOrder(TradingExampleWithOrderStatusListener.java:51)
	at com.sumzerotrading.ib.example.trading.TradingExampleWithOrderStatusListener.main(TradingExampleWithOrderStatusListener.java:115)

**Comment by rterp** [comment]
This is causing TradeOrder objects to not be persisted to the local filesystem in between TWS sessions.

**Comment by rterp** [comment]
Fixed
